site_name: NHF Robotics
site_url: http://robotdocs.com
theme: 
    name: lumen
    highlights: true
    features:
        - content.code.copy
        - content.code.select

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences  